language: node_js
node_js:
  - "4.4.2"
sudo: true

services: 
  - docker
before_install:
  - cd middleware

install:
  - npm install

script:
  - docker run -d -p 4567:4567 sagarkrkv/middleware

cache:
  directories:
    - node_modules

after_success:
  - docker login -u $DOCK_UNAME -p $DOCK_PWD
  - docker build -t sagarkrkv/middleware .
  - docker push sagarkrkv/middleware


before_deploy:
  - cd ..
  - zip -r B1.zip middleware/startup_scripts appspec.yml -x middleware/node_modules/**\* || true
  - mkdir -p "B1_upload"
  - mv B1.zip B1_upload/B1.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    bucket: sga-team-omega
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      repo: airavata-courses/TeamOmega
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-team-omega
    key: B1.zip
    bundle_type: zip
    application: SGA_TeamOmega
    deployment_group: SGA_TeamOmega
    region: us-west-2
    on:
      repo: airavata-courses/TeamOmega
      all_branches: true
after_deploy:
  - echo "Performing after deploy procedures..."
notifications:
  email:
    recipients:
      - vkalvaku@iu.edu
      - ssongire@iu.edu
  slack:
    secure: cE1uKN6FAfMdBAiRWHMOHVLo/DQqosbxNkYI2CAHMR34FVnrFBjYB49qfh8BuF+S4XmiuEBACJCqQvdSFwc4S6wp+jWsPhKmB5W+VsC+QDdCAiegRW3/h45ZMoupefOHNDF6iGmGu5Ck7xDNiJDxCdNaVqxYTsuaWlKC9ur4mutM5FNJGxXaH00qVHFl91jSq84EXSy4wfxRj/uc1PBRHzgpF9RE58O+5dZkhWYqFfrxGpiy3U6DqA49jKzJeRnVlqTagTJCMQqEMAx0AXieuJTPK69ZsTQ0aM3ouy/rZ0Vblw2GpB7FSBiYk7hybVhu568cM/+ZzCsKC9ZUtUaA0g+N8huvFigKvObrvwU7p/YpBcBFdxzVfiyRSPccPQ7myV4ibImxPF1JI0OMqvbzN85Mcp9rnpDcSxVEFFXPW+PUhCVtfbWhmEq8xCNCoMx95lzdxxhIRmVxNtJcpL7gaGliyiZm8YZIutevVCd9WdpH+fddToRV5XAhYO2HzTeGB0JImZczTf20rwbrKaqUXpMG2EGMk3mEJPBtfA7iU4WG5x1CiTQ00gW/0T6U9AxXwiFzu/X7+s2y7H9Xp3VcTfrTJXkJXLkYX0tAk12X1ksHp4weiRUhL955jz2fTUpFzlcS+AcOge7sXIMxgqq1NBm2omt1JavuerZok8zADfk=
