language: python
python:
  - "2.7"
cache: pip
install:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r Data_Ingestor/requirements.txt
script:
  - nosetests Data_Ingestor/UnitTests.py
