language: java
jdk:
  - oraclejdk8
sudo: false
install: true
services:
  - docker
before_install:
  - cd forecast_trigger

install:
  - true

after_success:
  - docker build -t sagarkrkv/forecast_trigger:latest .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCK_UNAME" -p="$DOCK_PWD"
  - docker push sagarkrkv/forecast_trigger:latest

before_deploy:
  - cd ..
  - zip -r Forecast_trigger.zip forecast_trigger/startup_scripts appspec.yml  || true
  - mkdir -p "Forecast_trigger_upload"
  - mv Forecast_trigger.zip Forecast_trigger_upload/Forecast_trigger.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    local_dir: Forecast_trigger_upload
    bucket: omega-m2
    region: us-east-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      repo: airavata-courses/TeamOmega
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: omega-m2
    key: Forecast_trigger.zip
    bundle_type: zip
    application: TeamOmega_east
    deployment_group: Omega_App_Server
    region: us-east-2
    on:
      repo: airavata-courses/TeamOmega
      all_branches: true
after_deploy:
  - echo "Performing after deploy procedures..."
notifications:
  email:
    recipients:
      - vkalvaku@iu.edu
      - ssongire@iu.edu
  slack:
secure: cE1uKN6FAfMdBAiRWHMOHVLo/DQqosbxNkYI2CAHMR34FVnrFBjYB49qfh8BuF+S4XmiuEBACJCqQvdSFwc4S6wp+jWsPhKmB5W+VsC+QDdCAiegRW3/h45ZMoupefOHNDF6iGmGu5Ck7xDNiJDxCdNaVqxYTsuaWlKC9ur4mutM5FNJGxXaH00qVHFl91jSq84EXSy4wfxRj/uc1PBRHzgpF9RE58O+5dZkhWYqFfrxGpiy3U6DqA49jKzJeRnVlqTagTJCMQqEMAx0AXieuJTPK69ZsTQ0aM3ouy/rZ0Vblw2GpB7FSBiYk7hybVhu568cM/+ZzCsKC9ZUtUaA0g+N8huvFigKvObrvwU7p/YpBcBFdxzVfiyRSPccPQ7myV4ibImxPF1JI0OMqvbzN85Mcp9rnpDcSxVEFFXPW+PUhCVtfbWhmEq8xCNCoMx95lzdxxhIRmVxNtJcpL7gaGliyiZm8YZIutevVCd9WdpH+fddToRV5XAhYO2HzTeGB0JImZczTf20rwbrKaqUXpMG2EGMk3mEJPBtfA7iU4WG5x1CiTQ00gW/0T6U9AxXwiFzu/X7+s2y7H9Xp3VcTfrTJXkJXLkYX0tAk12X1ksHp4weiRUhL955jz2fTUpFzlcS+AcOge7sXIMxgqq1NBm2omt1JavuerZok8zADfk=
