version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/clustering
hooks:
  BeforeInstall:
    - location: clustering/src/resources/scripts/before-install.sh
      runas: root
  ApplicationStart:
    - location: clustering/src/resources/scripts/install.sh
      timeout: 3600
      runas: root
  ValidateService:
    - location: clustering/src/resources/scripts/validate_service.sh
      timeout: 180
runas: root
