version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/TeamOmega
hooks:
  BeforeInstall: 
<<<<<<< HEAD
    - location: data_ingestor/startup_scripts/before-install.sh
      runas: root
      timeout: 300
    - location: middleware/startup_scripts/before-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: data_ingestor/startup_scripts/install.sh
      runas: root
      timeout: 240
    - location: middleware/startup_scripts/install.sh
=======
    - location: middleware/startup_scripts/dock_before_install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: middleware/startup_scripts/dock_install.sh
>>>>>>> 803d4080751264ba663564edde4c924a496f32e7
      runas: root
      timeout: 240
