version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: regsitry-api/build.sh
      runas: root
  ApplicationStart:
    - location: regsitry-api/run.sh
      timeout: 3600
      runas: root
