version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/TeamOmega
hooks:
  BeforeInstall: 
    - location: StormClustering/startup_scripts/before-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: StormClustering/startup_scripts/install.sh
      runas: root
      timeout: 240
