version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/TeamOmega
hooks:
  BeforeInstall: 
    - location: data_ingestor/startup_scripts/before-install.sh
      runas: root
      timeout: 300
    - location: middleware/startup_scripts/before-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: data_ingestor/startup_scripts/install.sh
      runas: root
      timeout: 240
    - location: middleware/startup_scripts/install.sh
      runas: root
      timeout: 240
